-- ANZ Agricrop product catalog seed. Run in the Supabase SQL Editor
-- against the live project. Safe to re-run: skips any slug that already
-- exists. Add more products by appending rows before the closing
-- `on conflict` clause.
--
-- Photos aren't handled here — attach each product's photo afterward via
-- the product edit form's photo upload field.

insert into products (name, slug, category, short_description, description, specs, traits, visible)
values
  ('Bottle Gourd F1 Julia', 'bottle-gourd-f1-julia', 'Gourds & Melons', 'Tender flesh, high yielding.', '', '{"Maturity Duration":"50 to 55 days after sowing","Fruit Shape":"Long cylindrical","Fruit Length":"55 to 55 cm","Fruit Weight":"500 to 600 gm","Fruit Colour":"Light Green"}'::jsonb, ARRAY['Hybrid']::text[], true),
  ('Bottle Gourd F1 Sophia', 'bottle-gourd-f1-sophia', 'Gourds & Melons', 'Tender flesh, very high yielding.', '', '{"Maturity Duration":"45 to 50 days after sowing","Fruit Shape":"Cylindrical type","Fruit Length":"40 to 45 cm","Fruit Weight":"400 to 500 gm","Fruit Colour":"Light Green"}'::jsonb, ARRAY['Hybrid']::text[], true),
  ('Okra F1 Glory', 'okra-f1-glory', 'Other Vegetables & Herbs', 'Good keeping quality.', '', '{"Plant Height":"3 to 4 feet","Branches":"Very Good","Internodes":"Short","Fruit Length":"7 to 9 cm","Fruit Colour":"Dark Green","Disease Tolerance":"YVMV, good productivity","Fruit Yield":"Very High"}'::jsonb, ARRAY['Hybrid']::text[], true),
  ('Bitter Gourd F1 Euro', 'bitter-gourd-f1-euro', 'Gourds & Melons', 'High yielding and suitable for long-duration harvest.', '', '{"Maturity Duration":"40 to 45 days after sowing","Fruit Shape":"Medium smooth","Fruit Length":"12 to 15 cm","Fruit Weight":"100 to 120 gm","Fruit Colour":"Dark Green"}'::jsonb, ARRAY['Hybrid']::text[], true),
  ('Bitter Gourd F1 Polo', 'bitter-gourd-f1-polo', 'Gourds & Melons', 'Good for long-distance transportation.', '', '{"Maturity Duration":"55 to 60 days after sowing","Fruit Shape":"Long spindle","Fruit Length":"16 to 18 cm","Fruit Weight":"100 to 120 gm","Fruit Colour":"Dark Green"}'::jsonb, ARRAY['Hybrid']::text[], true),
  ('Cucumber F1 Discovery', 'cucumber-f1-discovery', 'Gourds & Melons', 'Excellent taste; resistant to CMV, PRSV, ZYMV.', '', '{"Plant Habit":"Strong plant with dense foliage","Fruit Colour":"Light Green","Fruit Length":"18 to 20 cm","Fruit Diameter":"4 to 5 cm","Days of Maturity":"35 to 40 days","Fruit Weight":"400 to 500 gm"}'::jsonb, ARRAY['Hybrid']::text[], true),
  ('Cucumber F1 Poly', 'cucumber-f1-poly', 'Gourds & Melons', 'Excellent taste; resistant to CMV, PRSV, ZYMV.', '', '{"Plant Habit":"Strong plant with dense foliage","Fruit Colour":"Light Green","Fruit Length":"18 to 20 cm","Fruit Diameter":"4 to 5 cm","Days of Maturity":"35 to 40 days","Fruit Weight":"400 to 500 gm"}'::jsonb, ARRAY['Hybrid']::text[], true),
  ('Capsicum F1 Green', 'capsicum-f1-green', 'Solanaceous Vegetables', 'Green blocky, high-yielding hybrid for Kharif, Rabi, and mild summer; suitable for indoor and open cultivation.', '', '{"Plant Height":"2.5 feet","Days to 1st Picking":"60 to 65 days after transplanting","Fruit Weight":"80 to 100 gm","Fruit Colour Unripe":"Green","Fruit Colour Ripe":"Red"}'::jsonb, ARRAY['Hybrid']::text[], true),
  ('Capsicum F1 Wisdom', 'capsicum-f1-wisdom', 'Solanaceous Vegetables', 'Blocky, 3 to 4 lobes, good colour; suitable for indoor cultivation.', '', '{"Plant Height":"3.5 feet","Days to 1st Picking":"55 to 60 days after transplanting","Fruit Weight":"100 to 110 gm","Fruit Colour Unripe":"Green","Fruit Colour Ripe":"Red"}'::jsonb, ARRAY['Hybrid']::text[], true),
  ('Ridge Gourd F1 Laila', 'ridge-gourd-f1-laila', 'Gourds & Melons', 'Dark green hybrid, grown in Kharif and the summer season.', '', '{"Days to 1st Harvest":"40 to 50 days after sowing","Fruit Length":"55 to 60 cm","Fruit Colour":"Green","Seed Content":"Low","Fruit Weight":"120 to 130 gm"}'::jsonb, ARRAY['Hybrid']::text[], true),
  ('Chilli F1 Nat', 'chilli-f1-nat', 'Solanaceous Vegetables', 'Branches well with good flowering and fruit set; suitable for fresh green market, easy harvesting.', '', '{"Plant Height":"3 feet","Days to 1st Picking":"50 to 55 days after transplanting","Fruit Length":"14 to 16 cm","Fruit Diameter":"1 to 1.3 cm","Fruit Surface":"Medium smooth","Fruit Colour Unripe":"Light Green","Fruit Colour Ripe":"Red","Pungency":"Highly pungent"}'::jsonb, ARRAY['Hybrid']::text[], true),
  ('Chilli F1 Zeidan', 'chilli-f1-zeidan', 'Solanaceous Vegetables', 'Good for the fresh market; suitable for rainy and mild winter seasons with good heat tolerance.', '', '{"Plant Height":"3 feet","Days to 1st Picking":"60 to 65 days after transplanting","Fruit Length":"13 to 15 cm","Fruit Diameter":"1 to 1.2 cm","Fruit Surface":"Smooth","Fruit Colour Unripe":"Dark Green","Fruit Colour Ripe":"Red","Pungency":"Highly pungent"}'::jsonb, ARRAY['Hybrid']::text[], true),
  ('Chilli F1 Bill', 'chilli-f1-bill', 'Solanaceous Vegetables', 'Long fruits with very high pungency; grown in rainy, summer, and mild winter seasons.', '', '{"Plant Height":"3.5 feet","Days to 1st Picking":"60 to 65 days after transplanting","Fruit Length":"14 to 16 cm","Fruit Diameter":"1 to 1.2 cm","Fruit Surface":"Smooth","Fruit Colour Unripe":"Dark Green","Fruit Colour Ripe":"Red","Pungency":"Highly pungent"}'::jsonb, ARRAY['Hybrid']::text[], true),
  ('Watermelon F1 Honey', 'watermelon-f1-honey', 'Gourds & Melons', 'Vigorous plant with strong vines protecting against sunburn; good for long transport.', '', '{"Maturity":"80 to 85 days after sowing","Fruit Weight":"12 to 15 kg","Flesh Colour":"Light green rind with dark green stripes, bright red sweet and crispy flesh","Fruit Shape":"Oblong"}'::jsonb, ARRAY['Hybrid']::text[], true),
  ('Watermelon F1 Baby', 'watermelon-f1-baby', 'Gourds & Melons', 'Easy to grow with good fruit setting.', '', '{"Maturity":"60 to 65 days after sowing","Fruit Weight":"5 to 6 kg","Flesh Colour":"Black rind with red, juicy flesh","Fruit Shape":"Oblong"}'::jsonb, ARRAY['Hybrid']::text[], true),
  ('Tomato F1 Rome', 'tomato-f1-rome', 'Solanaceous Vegetables', 'Determinate hybrid tomato with good fruit firmness.', '', '{"Plant Habit":"Determinate","Maturity":"70 to 75 days","Fruit Shoulder":"Light Green","Fruit Weight":"80 to 90 gm","Fruit Shape":"Round","Fruit Firmness":"Good"}'::jsonb, ARRAY['Hybrid']::text[], true),
  ('Tomato F1 Dore', 'tomato-f1-dore', 'Solanaceous Vegetables', 'Medium to early hybrid, heat tolerant and good for long-distance transportation.', '', '{"Plant Habit":"Determinate","Maturity":"70 to 75 days","Fruit Shoulder":"Uniform Green","Fruit Weight":"90 to 100 gm","Fruit Shape":"Oval","Fruit Firmness":"Excellent","Disease Tolerance":"TYLCV"}'::jsonb, ARRAY['Hybrid']::text[], true),
  ('Tomato F1 Moriyan', 'tomato-f1-moriyan', 'Solanaceous Vegetables', 'Medium to early hybrid with excellent firmness; suitable for Rainy, Kharif, and Rabi season.', '', '{"Plant Habit":"Determinate","Maturity":"60 to 65 days","Fruit Shoulder":"Uniform Green","Fruit Weight":"80 to 90 gm","Fruit Shape":"Oval","Fruit Firmness":"Excellent"}'::jsonb, ARRAY['Hybrid']::text[], true),
  ('Tomato F1 King', 'tomato-f1-king', 'Solanaceous Vegetables', 'Good fruit quality.', '', '{"Plant Habit":"Indeterminate","Maturity":"65 to 70 days","Fruit Shoulder":"Uniform Green","Fruit Weight":"90 to 100 gm","Fruit Shape":"Round","Fruit Firmness":"Excellent"}'::jsonb, ARRAY['Hybrid']::text[], true),
  ('Cabbage F1 Dolphin', 'cabbage-f1-dolphin', 'Brassicas', 'Heat tolerant with excellent field-standing ability.', '', '{"Days to Maturity":"80 to 85 days","Head Shape":"Flat round","Head Colour":"Green","Head Weight":"2 to 2.5 kg"}'::jsonb, ARRAY['Hybrid']::text[], true),
  ('Carrot Red Core', 'carrot-red-core', 'Other Vegetables & Herbs', '', '', '{}'::jsonb, ARRAY['Open Pollinated']::text[], true),
  ('Cauliflower', 'cauliflower', 'Brassicas', '', '', '{}'::jsonb, ARRAY['Open Pollinated']::text[], true),
  ('Peas NZ', 'peas-nz', 'Other Vegetables & Herbs', '', '', '{}'::jsonb, ARRAY['Open Pollinated']::text[], true),
  ('Basil Green', 'basil-green', 'Other Vegetables & Herbs', '', '', '{}'::jsonb, ARRAY['Open Pollinated']::text[], true)
on conflict (slug) do nothing;
