export { productService } from './services/productService'
export { useProducts } from './hooks/useProducts'
export { useProduct, useRelatedProducts } from './hooks/useProduct'
export { useAdminProducts, useCreateProduct, useUpdateProduct, useSoftDeleteProduct } from './hooks/useAdminProducts'
export { default as ProductCard } from './components/ProductCard'
export { default as ProductGrid } from './components/ProductGrid'
export { default as ProductForm } from './components/admin/ProductForm'
export { default as ProductAdminList } from './components/admin/ProductAdminList'
export type { Product, ProductInput } from './types'
